version: 2
jobs:
  install:
    working_directory: ~/src
    docker:
        - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: make install
      - save_cache:
          key: twitterbot-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules

  test:
    working_directory: ~/src
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - twitterbot-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Running lint
          command: make lint
      - run:
          name: Running test
          command: make test
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Create TAG
          command: echo 'export TAG=$(eval echo ${CIRCLE_SHA1} | cut -c1-7)' >> $BASH_ENV
      - run:
          name: Login on Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Build Image
          command: docker build -t CodandoJuntas/twitterbot:${TAG} .
      - run:
          name: Send image to Docker Hub
          command: docker push CodandoJuntas/twitterbot:${TAG}

workflows:
  version: 2
  build-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
